name: Deploy corruption tracker API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-version:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Increment Docker image version
        id: versioning
        run: |
          # Извлекаем текущую версию из docker-compose.yml
          current_version=$(grep 'image: corruption-tracker-service:' docker-compose.yml | awk -F ':' '{print $3}')
          # Увеличиваем версию (например, 1.0 -> 1.1)
          new_version=$(echo $current_version | awk -F '.' '{print $1 "." $2+1}')
          echo "New version: $new_version"
          # Обновляем docker-compose.yml
          sed -i "s/corruption-tracker-service:$current_version/corruption-tracker-service:$new_version/" docker-compose.yml
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Commit and push updated version
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add docker-compose.yml
          git commit -m "Update Docker image version to ${{ env.new_version }}"
          git push
  deploy:
    runs-on: self-hosted
    needs: update-version
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: docker-compose
        run: docker-compose up -d
