name: Deploy corruption tracker API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-version:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Increment Docker image version
        id: versioning
        shell: pwsh
        run: |
          $content = Get-Content docker-compose.yml

          $currentVersion = ($content -match "image: corruption-tracker-service:(.+)$" | Out-String).Split(":")[-1].Trim()
      
          $newVersion = [string]([math]::Round(($currentVersion -replace '\.', ',') + 0.1, 1)).Replace(',', '.')
      
          Write-Host "Current version: $currentVersion"
          Write-Host "New version: $newVersion"
      
          $updatedContent = $content -replace "corruption-tracker-service:$currentVersion", "corruption-tracker-service:$newVersion"
          Set-Content docker-compose.yml $updatedContent
      
          echo "new_version=$newVersion" >> $GITHUB_ENV

      - name: Commit and push updated version
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add docker-compose.yml
          git commit -m "Update Docker image version to ${{ env.new_version }}"
          git push

  deploy:
    runs-on: self-hosted
    needs: update-version
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker Compose
        run: docker-compose up -d