name: Deploy corruption tracker API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  reset-environment:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        run: docker ps -q | ForEach-Object { docker stop $_ }
      - name: Remove unused data
        run: docker system prune -a -f
  prepare-environment:
    runs-on: self-hosted
    needs: reset-environment
    steps:
      - name: Create Docker network
        run: docker network create corruption-tracker-network || true
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: docker-compose
        run: docker-compose up -d
