name: Deploy corruption tracker API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-version:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Increment Docker image version
        id: versioning
        shell: bash
        run: |
          currentVersion=$(grep 'image: corruption-tracker-service:' docker-compose.yml | awk -F ':' '{print $3}')
          
          newVersion=$(echo $currentVersion | awk -F '.' '{print $1 "." $2+1}')
          echo "Current version: $currentVersion"
          echo "New version: $newVersion"
          
          sed -i "s/corruption-tracker-service:$currentVersion/corruption-tracker-service:$newVersion/" docker-compose.yml
          
          echo "new_version=$newVersion" >> $GITHUB_ENV


      - name: Commit and push updated version
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add docker-compose.yml
          git commit -m "Update Docker image version to ${{ env.new_version }}"
          git push

  deploy:
    runs-on: self-hosted
    needs: update-version
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker Compose
        run: docker-compose up -d